import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from 'Component/header'
import Hero from 'Component/hero'
import Footer from 'Component/footer'
import Content from 'Component/content'

export default function Home() {
  return (
    <app className='app'>
      <Head>
        <title>template</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet"/>
      </Head>
      <header className={styles.head}>
        <Header/>
      </header>
      <div className='hero'>
        <Hero/>
      </div>
      <main className={styles.main}>

        <Content/>

      </main>
      <footer className= {styles.footer}>
        <Footer/>
      </footer>
    </app>
  )
}
